version: '2'
services:
  Kibana:
    image: kibana
    stdin_open: true
    tty: true
    links:
    - Elastic:elasticsearch
    ports:
    - 5601:5601/tcp
    labels:
      io.rancher.container.pull_image: always
  Elastic:
    image: elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  Logstash:
    image: logstash
    stdin_open: true
    volumes:
    - /data/conf-logstatsh:/conf/logstash
    tty: true
    links:
    - Elastic:elasticsearch
    ports:
    - 5000:5000/tcp
    - 5000:5000/udp
    command:
    - -f
    - /conf/logstash/input-rsyslog.conf
    labels:
      io.rancher.container.pull_image: always
