version: '2'
services:
  KongaUI:
    image: pantsel/konga
    stdin_open: true
    tty: true
    links:
    - KongAPIsGateway:kong
    ports:
    - 1337:1337/tcp
    labels:
      io.rancher.container.pull_image: always
  kong-prepare-db:
    image: kong:latest
    environment:
      KONG_DATABASE: cassandra
      KONG_PG_HOST: kong-database
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    stdin_open: true
    tty: true
    links:
    - kong-db:kong-database
    command:
    - kong
    - migrations
    - up
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
  KongAPIsGateway:
    image: kong:latest
    environment:
      KONG_DATABASE: cassandra
      KONG_PG_HOST: kong-database
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    stdin_open: true
    tty: true
    links:
    - kong-db:kong-database
    ports:
    - 80:8000/tcp
    - 443:8443/tcp
    labels:
      io.rancher.container.pull_image: always
  kong-db:
    image: cassandra:3
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
